# Generated by Django 4.1.5 on 2023-05-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['-recipe'], 'verbose_name': 'Список покупок'},
        ),
        migrations.RemoveConstraint(
            model_name='recipeingridient',
            name='value_amount',
        ),
        migrations.RenameField(
            model_name='recipeingridient',
            old_name='ingridient',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='recipeingridient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='value_amount'),
        ),
    ]
